[IN PROGRESS] add google sheets service functions
phil-inc/pcommon pull request #3
Opened 2022-05-24 02:49 UTC by rachitamaharjan

2022-05-24 07:42 UTC, Swechhya requested changes

2022-05-24 07:42 UTC, Swechhya commented on data/config.go
> +package data
Lets keep this inside googl_sheet folder

2022-05-24 07:42 UTC, Swechhya commented on data/config.go
> +	Type            string `json:"type" bson:"type"`
We don not need bson and json tags here.

2022-05-26 08:40 UTC, SudipKatwal approved these changes

2022-05-27 03:42 UTC, Swechhya approved these changes

2022-05-27 07:04 UTC, chawocecil approved these changes

2022-05-27 09:55 UTC, varanasiaditya commented on pkg/network/README.md
> +      Type:            "type",
Formatting.

2022-05-27 12:51 UTC, Swechhya commented
@rachitamaharjan  Can you please resolve the merge conflicts?

2022-05-30 04:24 UTC, merged